import {
  ASSISTANT_BUTTON_LABEL,
  ASSISTANT_TOOLTIP_DESCRIPTION,
  ASSISTANT_TOOLTIP_TITLE,
} from '@/lib/assistant/constants';

/** @deprecated Use ASSISTANT_* — mantido para testes que ainda leem este arquivo. */
export const HELP_CENTER_SHOW_PROMO_BADGE = false;

export const HELP_CENTER_TOOLTIP_TITLE = ASSISTANT_TOOLTIP_TITLE;

export const HELP_CENTER_TOOLTIP_DESCRIPTION = ASSISTANT_TOOLTIP_DESCRIPTION;

export const HELP_CENTER_BUTTON_LABEL = ASSISTANT_BUTTON_LABEL;
