/** Colunas slim para carga inicial do mapa (sem select *). */
export const GIS_MAP_BLOCKS_SLIM_SELECT = [
  'id',
  'project_id',
  'tenant_id',
  'company_id',
  'number',
  'block_name',
  'name',
  'status',
  'price',
  'area',
  'perimeter',
  'geometry',
  'segments_json',
  'front_segment_index',
  'front_street_name',
  'front_street_type',
  'front_street_width',
  'front_street_id',
  'frente',
  'Fundo',
  'Lado Dir.',
  'Lado Esq.',
  'source_import',
  'customer_id',
  'sale_id',
  'contract_id',
  'updated_at',
  'projects(name)',
  'customers(name)',
].join(', ');
