/**
 * Allow-list explícita de tabelas/colunas para exportação F1 (tabular).
 */

import type { CompanyExportTableSpec } from '@/lib/master/companyExport/types';
import { COMPANY_EXPORT_FORBIDDEN_TABLES } from '@/lib/master/companyExport/denyList';

export const COMPANY_EXPORT_TABLES: readonly CompanyExportTableSpec[] = [
  // —— Empresa ——
  {
    id: 'companies',
    table: 'companies',
    folder: '01_empresa',
    fileBase: 'companies',
    scope: 'self_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'name',
      'fantasy_name',
      'cnpj',
      'email',
      'phone',
      'address',
      'city',
      'state',
      'zip_code',
      'slug',
      'status_operacional',
      'logo_url',
      'created_at',
      'updated_at',
    ],
    description: 'Cadastro da empresa (sem segredos)',
  },
  {
    id: 'company_subscriptions',
    table: 'company_subscriptions',
    folder: '01_empresa',
    fileBase: 'company_subscriptions',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'plan_id',
      'status',
      'contract_status',
      'started_at',
      'expires_at',
      'created_at',
      'updated_at',
    ],
    optional: true,
  },
  {
    id: 'users',
    table: 'users',
    folder: '01_empresa',
    fileBase: 'users',
    scope: 'tenant_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'full_name',
      'email',
      'phone',
      'role',
      'status',
      'tenant_id',
      'job_title',
      'last_login_at',
      'created_by',
      'created_at',
    ],
    description: 'Usuários do tenant via tenant_id (sem senha/hash/tokens)',
  },
  {
    id: 'invites',
    table: 'invites',
    folder: '01_empresa',
    fileBase: 'invites',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: ['id', 'email', 'role', 'tenant_id', 'company_id', 'status', 'created_at', 'expires_at'],
    optional: true,
  },
  {
    id: 'owner_project_access',
    table: 'owner_project_access',
    folder: '01_empresa',
    fileBase: 'owner_project_access',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'user_id',
      'project_id',
      'tenant_id',
      'company_id',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'company_financial_accounts',
    table: 'company_financial_accounts',
    folder: '01_empresa',
    fileBase: 'company_financial_accounts',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'name',
      'account_type',
      'beneficiary_name',
      'document',
      'email',
      'phone',
      'environment',
      'is_default',
      'active',
      'notes',
      'created_at',
      'updated_at',
    ],
    optional: true,
  },
  {
    id: 'bank_integrations',
    table: 'bank_integrations',
    folder: '01_empresa',
    fileBase: 'bank_integrations',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'provider',
      'environment',
      'status',
      'label',
      'bank_code',
      'agency',
      'account_number',
      'account_type',
      'is_default',
      'created_at',
      'updated_at',
    ],
    optional: true,
    description: 'Metadados bancários (sem credenciais)',
  },
  {
    id: 'technical_responsibles',
    table: 'technical_responsibles',
    folder: '01_empresa',
    fileBase: 'technical_responsibles',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: ['id', 'company_id', 'name', 'crea', 'cpf', 'email', 'phone', 'created_at'],
    optional: true,
  },

  // —— Clientes ——
  {
    id: 'customers',
    table: 'customers',
    folder: '02_clientes',
    fileBase: 'customers',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'name',
      'cpf_cnpj',
      'document',
      'phone',
      'email',
      'address',
      'city',
      'state',
      'zip_code',
      'created_at',
      'updated_at',
    ],
  },
  {
    id: 'customer_spouses',
    table: 'customer_spouses',
    folder: '02_clientes',
    fileBase: 'customer_spouses',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'customer_id',
      'name',
      'cpf_cnpj',
      'document',
      'phone',
      'email',
      'created_at',
      'updated_at',
    ],
    optional: true,
  },
  {
    id: 'customer_audit_logs',
    table: 'customer_audit_logs',
    folder: '02_clientes',
    fileBase: 'customer_audit_logs',
    scope: 'via_customers',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'customer_id',
      'action',
      'changed_by',
      'old_data',
      'new_data',
      'created_at',
    ],
    optional: true,
  },

  // —— Corretores ——
  {
    id: 'brokers',
    table: 'brokers',
    folder: '03_corretores',
    fileBase: 'brokers',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'name',
      'cpf',
      'creci',
      'phone',
      'email',
      'user_id',
      'active',
      'created_at',
      'updated_at',
    ],
  },
  {
    id: 'broker_commissions',
    table: 'broker_commissions',
    folder: '03_corretores',
    fileBase: 'broker_commissions',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'tenant_id',
      'broker_id',
      'sale_id',
      'contract_id',
      'customer_id',
      'amount',
      'percent',
      'status',
      'created_at',
      'updated_at',
    ],
    optional: true,
  },

  // —— Empreendimentos ——
  {
    id: 'projects',
    table: 'projects',
    folder: '04_empreendimentos',
    fileBase: 'projects',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'name',
      'city',
      'state',
      'address',
      'status',
      'financial_account_id',
      'created_at',
      'updated_at',
    ],
  },
  {
    id: 'blocks',
    table: 'blocks',
    folder: '04_empreendimentos',
    fileBase: 'blocks',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'project_id',
      'block_name',
      'number',
      'lot_number',
      'status',
      'area',
      'frente',
      'fundo',
      'customer_id',
      'created_at',
      'updated_at',
    ],
    jsonExtraColumns: ['segments_json', 'geometry'],
  },
  {
    id: 'lot_segments',
    table: 'lot_segments',
    folder: '04_empreendimentos',
    fileBase: 'lot_segments',
    scope: 'via_blocks',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'lot_id',
      'block_id',
      'segment_index',
      'length_m',
      'azimuth',
      'confrontante',
      'side',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'street_guides',
    table: 'street_guides',
    folder: '04_empreendimentos',
    fileBase: 'street_guides',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: ['id', 'tenant_id', 'project_id', 'name', 'created_at'],
    optional: true,
  },
  {
    id: 'project_confrontation_guides',
    table: 'project_confrontation_guides',
    folder: '04_empreendimentos',
    fileBase: 'project_confrontation_guides',
    scope: 'via_projects',
    formats: ['csv', 'json'],
    columns: ['id', 'project_id', 'name', 'created_at', 'updated_at'],
    optional: true,
  },
  {
    id: 'lot_audit_logs',
    table: 'lot_audit_logs',
    folder: '04_empreendimentos',
    fileBase: 'lot_audit_logs',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'block_id',
      'sale_id',
      'contract_id',
      'action',
      'old_data',
      'new_data',
      'created_at',
    ],
    optional: true,
  },

  // —— Vendas ——
  {
    id: 'sales',
    table: 'sales',
    folder: '05_vendas',
    fileBase: 'sales',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'project_id',
      'block_id',
      'customer_id',
      'broker_id',
      'status',
      'sale_date',
      'total_value',
      'payment_type',
      'financial_account_id',
      'created_at',
      'updated_at',
    ],
  },
  {
    id: 'sale_balloon_installments',
    table: 'sale_balloon_installments',
    folder: '05_vendas',
    fileBase: 'sale_balloon_installments',
    scope: 'via_sales',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'sale_id',
      'installment_number',
      'due_date',
      'amount',
      'status',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'sale_documents',
    table: 'sale_documents',
    folder: '05_vendas',
    fileBase: 'sale_documents_index',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'tenant_id',
      'project_id',
      'sale_id',
      'lot_id',
      'buyer_id',
      'category',
      'document_type',
      'description',
      'original_file_name',
      'storage_path',
      'mime_type',
      'file_size',
      'created_at',
      'deleted_at',
    ],
    optional: true,
    description: 'Índice de documentos (arquivos binários na F2)',
  },

  // —— Contratos ——
  {
    id: 'contracts',
    table: 'contracts',
    folder: '06_contratos',
    fileBase: 'contracts',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'sale_id',
      'customer_id',
      'project_id',
      'block_id',
      'contract_number',
      'status',
      'version',
      'pdf_url',
      'pdf_signed_url',
      'created_at',
      'updated_at',
    ],
    description: 'HTML em arquivos separados; signature_token omitido',
  },
  {
    id: 'contract_signatures',
    table: 'contract_signatures',
    folder: '06_contratos',
    fileBase: 'contract_signatures',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'contract_id',
      'customer_id',
      'signature_status',
      'signature_hash',
      'signed_at',
      'expires_at',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'contract_signature_parties',
    table: 'contract_signature_parties',
    folder: '06_contratos',
    fileBase: 'contract_signature_parties',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'contract_id',
      'contract_signature_id',
      'sale_id',
      'party_role',
      'party_name',
      'party_document',
      'status',
      'signed_at',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'signature_events',
    table: 'signature_events',
    folder: '06_contratos',
    fileBase: 'signature_events',
    scope: 'via_contracts',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'contract_id',
      'event_type',
      'actor',
      'ip_address',
      'user_agent',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'contract_templates',
    table: 'contract_templates',
    folder: '06_contratos',
    fileBase: 'contract_templates',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: ['id', 'tenant_id', 'company_id', 'name', 'active', 'created_at', 'updated_at'],
    jsonExtraColumns: ['content', 'html', 'body'],
    optional: true,
  },
  {
    id: 'legacy_contract_documents',
    table: 'legacy_contract_documents',
    folder: '06_contratos',
    fileBase: 'legacy_contract_documents_index',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'sale_id',
      'project_id',
      'storage_path',
      'original_file_name',
      'mime_type',
      'file_size',
      'created_at',
    ],
    optional: true,
    description: 'Índice (PDFs na F2)',
  },

  // —— Financeiro ——
  {
    id: 'finance_receipts',
    table: 'finance_receipts',
    folder: '07_financeiro',
    fileBase: 'finance_receipts',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'sale_id',
      'customer_id',
      'contract_id',
      'installment_number',
      'due_date',
      'amount',
      'paid_at',
      'status',
      'financial_account_id',
      'created_at',
      'updated_at',
    ],
  },
  {
    id: 'cash_movements',
    table: 'cash_movements',
    folder: '07_financeiro',
    fileBase: 'cash_movements',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'sale_id',
      'customer_id',
      'broker_id',
      'contract_id',
      'receipt_id',
      'type',
      'amount',
      'description',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'company_cash_movements',
    table: 'company_cash_movements',
    folder: '07_financeiro',
    fileBase: 'company_cash_movements',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'type',
      'amount',
      'description',
      'asaas_payment_id',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'company_asaas_charges',
    table: 'company_asaas_charges',
    folder: '07_financeiro',
    fileBase: 'company_asaas_charges',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'sale_id',
      'customer_id',
      'installment_id',
      'financial_account_id',
      'asaas_payment_id',
      'status',
      'bank_slip_url',
      'invoice_url',
      'amount',
      'due_date',
      'created_at',
      'updated_at',
    ],
    optional: true,
  },
  {
    id: 'company_asaas_webhook_events',
    table: 'company_asaas_webhook_events',
    folder: '07_financeiro',
    fileBase: 'company_asaas_webhook_events',
    scope: 'company_id',
    formats: ['json'],
    columns: ['id', 'company_id', 'event_type', 'created_at', 'raw_payload'],
    optional: true,
  },
  {
    id: 'bank_charges',
    table: 'bank_charges',
    folder: '07_financeiro',
    fileBase: 'bank_charges',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'integration_id',
      'finance_receipt_id',
      'sale_id',
      'customer_id',
      'status',
      'amount',
      'due_date',
      'created_at',
    ],
    optional: true,
  },
  {
    id: 'bank_cash_movements',
    table: 'bank_cash_movements',
    folder: '07_financeiro',
    fileBase: 'bank_cash_movements',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: ['id', 'company_id', 'amount', 'type', 'description', 'created_at'],
    optional: true,
  },
  {
    id: 'bank_webhook_events',
    table: 'bank_webhook_events',
    folder: '07_financeiro',
    fileBase: 'bank_webhook_events',
    scope: 'company_id',
    formats: ['json'],
    columns: ['id', 'company_id', 'provider', 'event_type', 'created_at', 'payload'],
    optional: true,
  },

  // —— Auditoria ——
  {
    id: 'audit_logs',
    table: 'audit_logs',
    folder: '09_auditoria',
    fileBase: 'audit_logs',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'tenant_id',
      'company_id',
      'user_id',
      'action',
      'module',
      'description',
      'details',
      'created_at',
    ],
  },
  {
    id: 'admin_logs',
    table: 'admin_logs',
    folder: '09_auditoria',
    fileBase: 'admin_logs',
    scope: 'company_or_tenant',
    formats: ['csv', 'json'],
    columns: ['id', 'tenant_id', 'company_id', 'user_id', 'action', 'details', 'created_at'],
    optional: true,
  },
  {
    id: 'data_migration_history',
    table: 'data_migration_history',
    folder: '09_auditoria',
    fileBase: 'data_migration_history',
    scope: 'company_id',
    formats: ['csv', 'json'],
    columns: [
      'id',
      'company_id',
      'migrated_at',
      'tipo',
      'arquivo',
      'usuario',
      'quantidade_total',
      'quantidade_importada',
      'quantidade_erros',
      'status',
      'created_at',
    ],
    optional: true,
  },
];

export function getExportTableById(id: string): CompanyExportTableSpec | undefined {
  return COMPANY_EXPORT_TABLES.find((t) => t.id === id);
}

export function assertRegistrySecurity(): void {
  for (const forbidden of COMPANY_EXPORT_FORBIDDEN_TABLES) {
    if (COMPANY_EXPORT_TABLES.some((t) => t.table === forbidden)) {
      throw new Error(`Registry inclui tabela proibida: ${forbidden}`);
    }
  }
  for (const spec of COMPANY_EXPORT_TABLES) {
    for (const col of [...spec.columns, ...(spec.jsonExtraColumns || [])]) {
      const lower = col.toLowerCase();
      if (
        lower === 'signature_token' ||
        lower === 'encrypted_payload' ||
        lower.includes('api_key') ||
        lower.includes('password')
      ) {
        throw new Error(`Registry coluna proibida em ${spec.table}.${col}`);
      }
    }
  }
}

export const COMPANY_EXPORT_CONTENT_SUMMARY = [
  'Cadastro da empresa, usuários e assinatura SaaS (sem segredos)',
  'Clientes, cônjuges e auditoria de clientes',
  'Corretores e comissões',
  'Empreendimentos, lotes, segmentos e guias (GeoJSON quando houver)',
  'Vendas e índice de documentos (arquivos binários na próxima fase)',
  'Contratos, HTML persistido, assinaturas (sem tokens ativos)',
  'Financeiro: parcelas, movimentos, cobranças (sem API keys)',
  'Auditoria e histórico de migração',
  'manifest.json e LEIA-ME',
] as const;
